version: '3'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    volumes:
      - .:/opt/
    ports:
      - '9000:9000'
    depends_on:
      - redis
      - nginx

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./static:/opt/static
    ports:
      - '8080:80'

  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    ports:
      - '6379:6379'
